name: flavours_united
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  rflutter_alert: ^2.0.4
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  file_picker: ^4.3.2
  chewie: ^1.2.2
  video_player: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: Slabo27px
      fonts:
        - asset: fonts/Slabo27px-Regular.ttf

    - family: Lora
      fonts:
        - asset: fonts/Lora-Regular.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
